# Generated by Django 5.2 on 2025-07-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='issue_type',
        ),
    ]
