# Generated by Django 5.2 on 2025-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_type_issue_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='signed_date',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='date_activated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
