# Generated by Django 5.2 on 2025-07-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_leaseagreement_signed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='tenant',
            new_name='user',
        ),
    ]
