# Generated by Django 5.2 on 2025-07-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_tenant_leaseagreement_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='tenant',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tenantprofile',
            old_name='tenant',
            new_name='user',
        ),
    ]
