# Generated by Django 5.2 on 2025-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_rename_tenant_notification_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='tenant',
            new_name='user',
        ),
    ]
