# Generated by Django 5.2 on 2025-07-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_rename_tenant_issue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymanager',
            old_name='manager',
            new_name='user',
        ),
    ]
