# Generated by Django 5.2 on 2025-07-28 15:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_rename_manager_propertymanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of servicing the issue (in Rands)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('flat', 'Flat')], default='apartment', max_length=255),
        ),
    ]
